### ISSUE TITLE
hi，大佬，晚上好！

### ISSUE THREAD

**Issue by y377** [iBug/iBug-source#10]
首先请问大佬：
![image](https://user-images.githubusercontent.com/58632405/166447312-3cf27a75-8199-4745-9a60-e567b1a3de2d.png)
这是什么操作？正向代理？
---------------------------

> 无意中发现大佬的博客，是我喜欢的类型！

正题：关于代码段/代码一键复制的问题，想请教一下大佬！
首先请大佬看我想实现的效果图，右上添加一键复制按钮！
当前：未实现。
![image](https://user-images.githubusercontent.com/58632405/166447781-65f649a8-7bc3-4d35-ab89-89b8726b140f.png)
我也使用的[clipboardjs](https://clipboardjs.com/)，但是代码高亮我用的是[highlight.js](https://github.com/highlightjs/highlight.js)；跟大佬们用的Jekyll官方插件不同，这就造成一个问题，你们几位在[Adding Copy to Clipboard button to minimal-mistakes with clipboard.js](https://gh.fakev.cn/mmistakes/minimal-mistakes/discussions/2795)讨论的方法/实现对于我的组建好像不适用，
我也尝试了，还是失败，不知道是不是我因为前面有代码行号的原因。
   
#### 疑问点：
 `var codeChunk = document.querySelectorAll("pre > code");`
我`document.querySelectorAll()`应该怎么填？因为不同代码语言这里会变；
比如第一个代码段是bash：`class="language-bash hljs"`
第二个代码段是JavaScript：`class="language-javascript hljs"`
   
------------------
![image](https://user-images.githubusercontent.com/58632405/166448590-2d05b50e-ef1a-4e51-859e-d955e636b1f4.png)
-----------------
**所以无奈想请问大佬能否点拨一二？**

**Comment by iBug** [comment]
## 1

没听说过这个域名，网上的 GitHub 代理很多，这就是其中之一，没有什么特别的地方，例如 <https://hub.fastgit.xyz>。

## 2

我自己实现的版本已经在 [PR #2812](https://github.com/mmistakes/minimal-mistakes/pull/2812/files) 里给出了，原理就是找到代码块（`document.querySelectorAll`）然后在 `<pre> <code>` 中间插入一个 button 元素，并设置点击时的 eventListener。

以我的实现为例，点击时的 eventListener 从 button 本身开始在 DOM 的同一级往后找 `<code>`，取找到的 `<code>` 内容作为要复制的内容。根据你的截图，有了行号之后每个 `<pre>` 里有两个 `<code>` 了，所以你需要自己修改 JS 让它找真正的代码，而不是找到存行号的那个 `<code>`（我猜这就是你遇到的问题，点按钮把行号复制出来了）。

另外我的实现假设每个 `<pre>` 只有一个 `<code>` 并在 code 前插入 button，对于你的情况可以把 querySelectorAll 改成 `pre > code:first-child` 确保只在第一个 code 前加按钮，class 什么的可以不用管。

初步看来改好这两处就差不多了。

**Comment by y377** [comment]
好的，谢谢大佬的回复，当前并未成功，且被[highlight.js](https://github.com/highlightjs/highlight.js)报警告⚠提示，认为没有初始化HTML，不安全什么的；余下的我再搜搜相关文档，再次谢谢！如果想到什么，欢迎补充☺

**Comment by y377** [comment]
#### 用其他方法实现了，但是有bug！
https://user-images.githubusercontent.com/58632405/166627794-ad43846f-f2a5-4795-8cad-ad9b8e6691f7.mp4

----------------
#### 你大佬的方法
![image](https://user-images.githubusercontent.com/58632405/166627909-f16ee441-0cd4-492b-823a-f7ee745001f2.png)

**Comment by iBug** [comment]
那是你自己加了别的东西吧，我看你的 `<pre>` 上面多了个 `display: flex`，这可不是主题提供的样式，并且也没有很好的办法在 flex 里面搞 float，你需要自己想办法了。
