### ISSUE TITLE
how to install proxmox on emmc

### ISSUE THREAD

**Issue by onlineapps-cloud** [iBug/iBug-source#11]
hi, i read your article on your blog about installing proxmox on emmc 
https://ibug.io/blog/2022/03/install-proxmox-ve-emmc/
i tried to install latest proxmox on SBC with emmc
i edited /usr/share/perl5/Proxmox/Sys/Block.pm.
but i had another error:
![2024-02-26-18-15-46-667](https://github.com/iBug/iBug-source/assets/69077240/819046d6-0f54-43e8-a79c-0b1e2f5ac758)
i oppened this file and follow to 906 line:
![2024-02-26-18-20-07-812](https://github.com/iBug/iBug-source/assets/69077240/659b3d01-714b-47d2-b68a-188101b8f2f1)
very strange, i think instruction is not compatible with latest proxmox build? how to fix it?. best regards.

**Comment by iBug** [comment]
Try asking on Proxmox forums. Note that the output from the `unsquashfs` command is definitely **required**.
